--인덱스
SELECT INDEX_NAME, TABLE_NAME, TABLESPACE_NAME, TABLE_OWNER FROM USER_INDEXES;
--ALTER INDEX 인덱스명 REBUILD TABLESPACE 테이블스페이스;

--테이블
SELECT TABLE_NAME, TABLESPACE_NAME FROM USER_TABLES;
--ALTER TABLE 테이블명 MOVE TABLESPACE 테이블스페이스;
